import type { IceServer } from "./types";

export const defaultIceServers: IceServer[] = [
  { urls: "stun:stun.l.google.com:19302" },
  { urls: "stun:stun1.l.google.com:19302" },
];

export const MONTHLY_CAP_BYTES = 1000 * 1024 * 1024 * 1024;

export const INITIAL_ICE_ROUTE = "Ищем маршрут...";
export const INITIAL_TRAFFIC_ROUTE_LABEL = "Определяем маршрут трафика...";

export const SILENT_KEEPALIVE_AUDIO =
  "data:audio/mp3;base64,SUQzAwAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4LjMyLjEwMQAAAAAAAAAAAAAA//uQxAADBzQABpAAAANIAAAAAExBTUUzLjk4LjIAAAAAAAAAAAAAAP/7kMQAAgc0AAaQAAACQAAAABBMQU1FMy45OC4yAAAAAAAAAAAAAAD/+5DEAAIHNAAGkAAAAkAAAAAQTEFNRTMuOTguMgAAAAAAAAAAAAAA//uQxAADBzQABpAAAANIAAAAAExBTUUzLjk4LjIAAAAAAAAAAAAAAP/7kMQAAgc0AAaQAAACQAAAABBMQU1FMy45OC4yAAAAAAAAAAAAAAD/+5DEAAIHNAAGkAAAAkAAAAAQTEFNRTMuOTguMgAAAAAAAAAAAAAA";
